# Generated by Django 4.2.5 on 2023-10-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Anbieter",
            fields=[
                ("url", models.CharField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "Anbieter",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Einzelteil",
            fields=[
                ("einzelteil_id", models.CharField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "Einzelteil",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Legoset",
            fields=[
                ("set_id", models.CharField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "Legoset",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EinzelteilLegoset",
            fields=[
                (
                    "einzelteil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="tutorials.einzelteil",
                    ),
                ),
                ("anzahl", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "Einzelteil_legoset",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Einzelteilmarktpreis",
            fields=[
                (
                    "einzelteil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="tutorials.einzelteil",
                    ),
                ),
                ("preis", models.FloatField(blank=True, null=True)),
                ("url", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "EinzelteilMarktpreis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Setmarktpreis",
            fields=[
                (
                    "set",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="tutorials.legoset",
                    ),
                ),
                ("preis", models.FloatField(blank=True, null=True)),
                ("url", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "SetMarktpreis",
                "managed": False,
            },
        ),
    ]
